package com.example.moviewatchkatalog

import android.content.Intent
import android.os.Bundle
import android.widget.ImageView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {

    private val list = ArrayList<Movie>()
    private lateinit var rvMovies: RecyclerView
    private lateinit var movieAdapter: MovieAdapter

    private val movieList = listOf(
        Movie("Venom", "Eddie Brock (Tom Hardy) adalah seorang jurnalis investigatif berbakat yang dikenal karena keberaniannya dalam mengungkap kebenaran, meskipun seringkali dengan cara yang kontroversial. Ketika dia memutuskan untuk menyelidiki Life Foundation, sebuah organisasi besar yang dipimpin oleh ilmuwan ambisius Dr. Carlton Drake (Riz Ahmed), dia menemukan lebih dari yang pernah dia bayangkan. Life Foundation sedang melakukan eksperimen rahasia dengan Symbiote, makhluk alien yang memerlukan tubuh manusia sebagai inang untuk bertahan hidup. Namun, proses ini sangat berbahaya dan mematikan bagi manusia yang menjadi inangnya. Saat Eddie menyelinap ke dalam laboratorium untuk mencari bukti, dia secara tidak sengaja terinfeksi oleh salah satu Symbiote. Symbiote yang bernama Venom ini mengubah Eddie secara drastis, memberinya kekuatan super, namun dengan harga mahal: Eddie harus berjuang untuk mengendalikan entitas Venom yang juga memiliki keinginannya sendiri. Di tengah kekacauan ini, Eddie dan Venom membentuk aliansi yang aneh untuk menghentikan rencana jahat Dr. Drake yang berencana menggunakan Symbiote untuk menguasai umat manusia. Film ini menggambarkan konflik moral Eddie, di mana dia harus memilih antara menggunakan kekuatan barunya untuk kebaikan atau jatuh ke dalam kehancuran yang ditawarkan oleh Venom.", R.drawable.film1, "2018", "7.1/10","Ruben Fleischer", "Jeff Pinkner, Scott Rosenberg"),
        Movie("Joker", "Arthur Fleck (Joaquin Phoenix) adalah seorang pria kesepian yang hidup di Gotham City, sebuah kota penuh dengan ketidakadilan, kekerasan, dan kemiskinan. Arthur, yang menderita gangguan mental, bekerja sebagai badut untuk acara anak-anak dan bermimpi menjadi seorang komedian. Namun, kenyataan hidupnya jauh dari impian itu. Setiap hari, ia berjuang melawan kesedihan, diejek oleh orang-orang di sekitarnya, dan diabaikan oleh masyarakat. Arthur merasa dirinya semakin terisolasi, hingga suatu hari serangkaian kejadian kejam dan kekerasan mulai mendorongnya ke tepi kegilaan. Setelah diserang di kereta bawah tanah, Arthur secara brutal membunuh tiga orang penyerangnya, yang kemudian menempatkannya sebagai simbol revolusi di kota yang dipenuhi ketidakpuasan sosial. Seiring berjalannya waktu, Arthur sepenuhnya berubah menjadi Joker, seorang pria tanpa moral yang mewakili kekacauan total. Film ini mengeksplorasi perjalanan psikologis Arthur, dari pria terpinggirkan yang berjuang untuk diterima, menjadi simbol anarki yang memicu pemberontakan di Gotham. Ini adalah cerita tentang bagaimana kegilaan bisa timbul dari kekejaman dunia, dan bagaimana masyarakat terkadang menciptakan monster dari orang-orang yang mereka abaikan.", R.drawable.film2, "2019", "8.5/10","Todd Phillips","Todd Phillips, Scott Silver" ),
        Movie("Fast & Furious 9", "Setelah bertahun-tahun menghadapi musuh-musuh yang tangguh, Dominic Toretto (Vin Diesel) mencoba melarikan diri dari kehidupan lamanya yang penuh bahaya untuk menjalani hidup tenang bersama keluarganya, Letty (Michelle Rodriguez) dan putra kecil mereka, Brian. Namun, kedamaian mereka tidak berlangsung lama. Sebuah ancaman baru muncul, kali ini lebih dekat dari yang pernah Dom bayangkan. Jakob (John Cena), saudara laki-laki Dom yang telah lama terpisah, kembali muncul dalam kehidupannya, membawa dendam yang terpendam. Jakob, yang kini menjadi pembunuh bayaran dan pengemudi handal, bekerja sama dengan organisasi rahasia yang memiliki rencana untuk menggunakan teknologi canggih demi menguasai dunia. Dom, bersama timnya, harus berhadapan dengan musuh lamanya dan menghadapi masa lalunya yang penuh rahasia. Persaingan antara Dom dan Jakob bukan hanya tentang pertempuran untuk menyelamatkan dunia, tetapi juga pertempuran keluarga yang sarat dengan rasa pengkhianatan dan penebusan. Film ini menawarkan aksi intens dan mendalam tentang ikatan keluarga, kesetiaan, dan pengorbanan.", R.drawable.film3, "2021", "5.2/10","Justin Lin","Daniel Casey, Justin Lin"),
        Movie("Spider-Man: No Way Home", "Hidup Peter Parker (Tom Holland) berubah selamanya setelah identitasnya sebagai Spider-Man terbongkar ke publik oleh Mysterio. Akibatnya, Peter dan orang-orang yang dicintainya, termasuk MJ (Zendaya) dan Aunt May (Marisa Tomei), terjebak dalam sorotan publik dan menjadi sasaran berbagai serangan. Dalam upaya untuk membalikkan keadaan, Peter meminta bantuan Doctor Strange (Benedict Cumberbatch), seorang penyihir dengan kekuatan luar biasa, untuk membuat dunia melupakan bahwa dia adalah Spider-Man. Namun, mantra yang dilancarkan oleh Doctor Strange berjalan salah dan merusak realitas, membuka portal ke multiverse yang memungkinkan musuh-musuh dari dimensi lain datang ke dunia Peter. Musuh-musuh lama seperti Green Goblin (Willem Dafoe), Doctor Octopus (Alfred Molina), dan Electro (Jamie Foxx) datang untuk menghancurkan hidup Peter. Di tengah kekacauan, Peter juga bertemu dengan versi dirinya dari dimensi lain yang diperankan oleh Tobey Maguire dan Andrew Garfield. Mereka harus bekerja sama untuk memperbaiki kerusakan yang telah terjadi, melawan musuh-musuh mereka, dan menemukan kembali arti tanggung jawab yang diemban sebagai Spider-Man.", R.drawable.film4, "2021", "8.7/10","Jon Watts","Chris McKenna, Erik Sommers"),
        Movie("Meg 2: The Trench", "Jonas Taylor (Jason Statham), seorang penyelam penyelamat profesional, kembali ke kedalaman samudra untuk sebuah misi baru yang lebih berbahaya dari sebelumnya. Kali ini, dia bergabung dengan tim peneliti untuk menjelajahi Palung Mariana, tempat makhluk-makhluk purba yang belum pernah ditemukan manusia. Penemuan mereka mengungkapkan bahwa di bawah lautan terdalam ini, ada lebih dari sekadar keindahan laut; terdapat predator kuno yang lebih besar dan lebih berbahaya dari Megalodon, yang pernah mereka hadapi sebelumnya. Ancaman menjadi semakin nyata ketika operasi penambangan rahasia di dasar laut memicu serangkaian peristiwa berbahaya, melepaskan beberapa Meg yang lebih besar ke perairan terbuka. Tim Jonas harus berjuang untuk bertahan hidup melawan para monster laut ini sambil menghentikan perusahaan jahat yang bertanggung jawab atas kekacauan tersebut. Film ini membawa aksi mendebarkan dan visual spektakuler dari pertarungan antara manusia dan predator raksasa di kedalaman lautan yang belum dijelajahi.", R.drawable.film5, "2023", "5.6/10","Ben Wheatley","Jon Hoeber, Erich Hoeber"),
        Movie("Godzilla x Kong: The New Empire", "Setelah pertempuran epik antara Godzilla dan Kong di film sebelumnya, dunia kini menghadapi ancaman yang lebih besar dan misterius. Para titan mulai menunjukkan perilaku aneh, seolah-olah sesuatu atau seseorang sedang memanggil mereka. Penemuan arkeologi kuno mengungkapkan bahwa ada kekuatan lain yang lebih kuat dan lebih tua dari Godzilla maupun Kong, sebuah entitas purba yang telah lama tertidur. Ketika ancaman baru ini bangkit, Godzilla dan Kong, yang dulu menjadi musuh bebuyutan, kini harus bersatu untuk melawan musuh bersama yang dapat menghancurkan seluruh planet. Film ini membawa para penonton ke pertempuran yang lebih epik, dengan visual luar biasa dan pertempuran kolosal antara makhluk-makhluk raksasa. Selain itu, manusia juga terlibat dalam konflik ini, dengan beberapa ilmuwan dan militer berusaha memahami dan memanfaatkan kekuatan titan untuk kepentingan mereka sendiri.", R.drawable.film6, "2024", "N/A","Adam Wingard","Terry Rossio, Michael Dougherty"),
        Movie("Transformers: The Last Knight", "Setelah letusan gunung berapi menghancurkan Isla Nublar, pulau yang menjadi rumah bagi dinosaurus, Claire Dearing (Bryce Dallas Howard) dan Owen Grady (Chris Pratt) memimpin misi penyelamatan untuk menyelamatkan spesies dinosaurus yang tersisa. Namun, mereka segera mengetahui bahwa penyelamatan ini hanyalah awal dari konspirasi yang lebih besar. Eli Mills, seorang pengusaha kaya, bermaksud untuk menjual dinosaurus-dinosaurus tersebut kepada para pembeli di pasar gelap sebagai senjata biologis. Hal ini membuat Claire dan Owen tidak hanya harus menyelamatkan dinosaurus, tetapi juga menghentikan lelang yang berpotensi membawa kehancuran besar. Dalam prosesnya, mereka menemukan spesies dinosaurus baru yang berbahaya, Indoraptor, yang telah direkayasa genetis sebagai pembunuh sempurna. Indoraptor kabur dan mulai meneror semua orang di sekitar perkebunan tempat dinosaurus disimpan. Owen dan Claire harus berjuang untuk menghentikan makhluk ini sebelum terlambat, sekaligus memutuskan nasib masa depan dinosaurus di dunia manusia.", R.drawable.film7, "2017", "5.2/10","Michael Bay","Art Marcum, Matt Holloway"),
        Movie("Jurassic World: Fallen Kingdom", "Setelah Isla Nublar porak-poranda akibat letusan gunung berapi, spesies dinosaurus yang tersisa dibawa ke perkebunan Lockwood yang besar, di Amerika. Di tempat tersebut, Owen dan Claire menyadari bahwa spesies dinosaurus malah dilelang dan tidak dilestarikan. Seekor dinosaurus hibrida yang sangat berbahaya dan dikenal dengan nama Indoraptor, kabur dan mulai meneror penduduk di sekitar perkebunan.", R.drawable.film8, "2018", "6.1/10","J.A. Bayona","Colin Trevorrow, Derek Connolly"),
        Movie("Man of Steel", "Kal-El (Henry Cavill) adalah satu-satunya penyintas dari planet Krypton yang dihancurkan. Dikirim ke Bumi sebagai bayi oleh orang tuanya yang ingin menyelamatkannya dari kehancuran planet mereka, Kal tumbuh di bawah asuhan keluarga Kent di Kansas. Dengan identitas baru sebagai Clark Kent, ia berjuang untuk memahami dirinya dan kekuatan luar biasa yang dimilikinya, seperti terbang, kekuatan super, dan penglihatan sinar-X. Ketika General Zod (Michael Shannon), mantan prajurit dari Krypton, datang ke Bumi dengan tujuan menghancurkannya dan membangun kembali Krypton di atasnya, Clark harus memilih nasibnya. Apakah dia akan menjadi simbol harapan bagi umat manusia atau musuh yang berbahaya? Sebagai Superman, Clark harus menghadapi Zod dalam pertempuran epik yang tidak hanya akan menentukan nasib Bumi tetapi juga menentukan apa artinya menjadi seorang pahlawan. Film ini mengeksplorasi bagaimana Clark menemukan identitasnya sebagai Superman, bagaimana ia belajar mengendalikan kekuatannya, dan tanggung jawab besar yang datang bersamaan dengan kekuatan itu.", R.drawable.film9, "2013", "7.1/10","Zack Snyder","David S. Goyer"),
        Movie("World War Z", "World War Z merupakan film horor kiamat tahun 2013 yang disutradarai Marc Forster. Skenario yang ditulis Matthew Michael Carnahan ini didasarkan pada novel tahun 2006 berjudul sama karya Max Brooks.", R.drawable.film10, "2013", "7.0/10","Marc Forster","Matthew Michael Carnahan")
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        rvMovies = findViewById(R.id.rv_movies)
        rvMovies.layoutManager = LinearLayoutManager(this)
        movieAdapter = MovieAdapter(movieList)
        rvMovies.adapter = movieAdapter

        val imageView = findViewById<ImageView>(R.id.icon_profile)
        imageView.setOnClickListener {
            val intent = Intent(this, ProfileActivity::class.java)
            startActivity(intent)
        }
    }
}